src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MessageRepository::class)]
class Message
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Title = null;

    #[ORM\Column(length: 255)]
    private ?string $Content = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Attachment = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getAttachment(): ?string
    {
        return $this->Attachment;
    }

    public function setAttachment(?string $Attachment): self
    {
        $this->Attachment = $Attachment;

        return $this;
    }
}

src/Controller/MainPageController.php
<?php

namespace App\Controller;

use App\Entity\Admin;
use App\Entity\Products;
use App\Entity\User;
use App\Repository\ProductsRepository;
use App\Services\FileUploader;
use App\Form\CreateType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
//#[Route('/user', name: 'user.')]
class MainPageController extends AbstractController
{

    #[Route('/', name: 'main_page')]
    public function index(UserRepository $userRepository, ProductsRepository $productsRepository): Response
    {
//        $title = "Tytuł";
        $user = $userRepository->findAll();
        $products = $productsRepository->findAll();
        return $this->render('main_page/index.html.twig', [
//            'title' => $title,
            'user' => $user,
            'products' => $products
        ]);
    }
    #[Route('/profile', name: 'profile')]
    public function profile(UserRepository $userRepository)
    {
        $user = $this->getUser();
//        dd($user);
        return $this->render('main_page/profile.html.twig', [
            'user' => $user
        ]);
    }

    #[Route('/products/{id}', name: 'products')]
    public function showProducts($id, ProductsRepository $productsRepository): Response
    {
        $products = $productsRepository->find($id);
//        $id =$request->attributes->all()["id"];
////        dd($request->attributes->all()["id"]);
//        $products = $this->
        return $this->render('main_page/show.html.twig', [
            "product" => $products
        ]);

    }

}

templates/main_page/index.html.twig
{% extends 'base.html.twig' %}
{% block head %}
    <head>
        <title>Sklep</title>

        {% block stylesheets %}
            <style>
               
                .products__element-description {
                    font-size: 14px;
                }
                .products__element-image {
                    width: 100px;
                    height: 100px;
                }
            </style>
        {% endblock %}
    </head>
{% endblock %}
{% block body %}

    <h1>Witaj!</h1>

    <br>
    <!-- Slider main container -->

            {% for product in products %}

                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{{ "/uploads/" ~ product.attachment }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.title }}</h5>
                        <div class="card-text"><p class="products__element-description">{{ product.description }}</p></div>
                        <a href="{{ path('products', {id: product.id}) }}"><button class="btn btn-primary">Więcej Informacji</button></a>
                        {% if(is_granted("ROLE_ADMIN"))%}
                            <a href="{{ path("admin_product_delete", {id: product.id}) }}"><button class="btn btn-danger">Usuń</button></a>
                        {% endif %}
                    </div>
                </div>
                <br>
            {% endfor %}







{% endblock %}

templates/main_page/profile.html.twig
{% extends 'base.html.twig' %}


    {% block body %}
        <h1>Witaj {{ user.getName() }}!</h1>
        <p>Email: {{ user.getEmail() }}</p>
        <p>Hasło: *********** <a href="{{ path('change_password') }}"><button class="btn btn-warning">Zmień hasło</button></a></p>


    {% endblock %}

templates/main_page/show.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('/css/style.css') }}">
{% endblock %}
{% block body %}

    <img class="products__image" src="{{"/uploads/" ~ product.attachment }}" alt="">
    <h1>{{ product.title }}</h1>
    <p>Opis: {{ product.description }}</p>

    <p>Ilość: {{ product.count }}</p>
    {% if(product.count == 0) %}
    <p>Dostępne: {{ product.sold_out }}</p>
    {% endif %}
    <p>Cena: {{ product.price }} zł</p>

    <a href=""><button class="btn btn-success">Kup</button></a>
{% endblock %}